name: Build DanmakuFactory

on:
  push:
    branches:
      - master  # 推送到 master 分支时触发
  pull_request:
    branches:
      - master  # 针对 master 分支的拉取请求时触发
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: windows-latest  # 使用最新的 Windows 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 检出代码

    - name: Build
      run: |
        mingw32-make -f makefile-win  # 使用 mingw32-make 编译项目

    - name: Upload executable
      uses: actions/upload-artifact@v3  # 使用 v3 版本
      with:
        name: DanmakuFactory.exe
        path: DanmakuFactory.exe  # 根据实际输出文件路径调整
        
    - name: List files
      run: dir  # 在 Windows 上列出当前目录的文件

    - name: Check MinGW version
      run: gcc --version  # 检查 GCC 版本和位数
