name: Build DanmakuFactory

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        mingw32-make -f makefile-win

    - name: Get current date and time
      id: vars
      run: |
        echo "RELEASE_VERSION=v$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
        echo "RELEASE_NAME=DanmakuFactory $(date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: ${{ env.RELEASE_NAME }}
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload executable
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: DanmakuFactory.exe
        asset_name: DanmakuFactory.exe
        asset_content_type: application/octet-stream
