name: Build DanmakuFactory

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        mingw32-make -f makefile-win

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: DanmakuFactory.exe
        path: DanmakuFactory.exe
