name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "00 15 * * *" # 每天15:00执行
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # Step 1: Checkout target repo
      - name: Checkout target repo
        uses: actions/checkout@v3

      # Step 2: Sync upstream changes
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: hihkm/DanmakuFactory
          upstream_sync_branch: master
          target_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}  # 自动生成的token
          test_mode: false

      - name: Sync check
        if: failure()
        run: |
          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，详细教程请查看项目README.md"
          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the project README.md for instructions."
          exit 1

      # 触发构建工作流
      - name: Trigger Build Workflow
        if: success()  # 仅在成功时触发
        uses: octokit/request-action@v2.4.0  # 使用 octokit/request-action
        with:
          route: POST /repos/${{ github.repository }}/dispatches
          mediaType: '{"accept": "application/vnd.github.v3+json"}'
          event_type: "trigger-build"  # 直接传递 event_type
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 设置 GITHUB_TOKEN
